theme: jekyll-theme-minimal

title: Ryan M. Carlson
description: Image Analyst at Maxar Technologies
show_downloads: false

plugins:
  - jekyll-feed

feed:
   posts_limit: 3
   categories:
      - coding
      - outdoors
